name: Greeting Workflow

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Starting message
        run: echo "Starting my greeting workflow"

      - name: Print name and date
        run: echo "Karan Singh and today is $(date)"